defaults:
  - _self_
  - robot: g1_29dof_anneal_23dof
  - obs: deepmimic_a2c_nolinvel_LARGEnoise_history

policy_path: null

simulation_dt: 0.001

# Simulation parameters
total_time: 10.0  # Total simulation time in seconds
policy_dt: 0.02   # Policy frequency (50Hz)
motion_length: 3.97  # Motion cycle length in seconds

video:
  enabled: true
  path: "my_video.mp4"
  width: 960
  height: 1280
  camera_settings:
    distance: 2.0
    azimuth: 45.0 # degrees
    elevation: -25.0 # degrees
    lookat_body: "pelvis"

hydra:
  job:
    chdir: False
