# @package _global_

algo:
  _target_: humanoidverse.agents.ppo.ppo.PPO
  _recursive_: False
  config:
    num_learning_epochs: 5
    num_mini_batches: 4
    clip_param: 0.2
    gamma: 0.99
    lam: 0.95
    value_loss_coef: 1.0
    entropy_coef: 0.01
    actor_learning_rate: 1.e-3 # 5e-4 # 1.e-3
    critic_learning_rate: 1.e-3 # 5e-4 # 1.e-3
    max_grad_norm: 1.0
    use_clipped_value_loss: True
    schedule: "adaptive"
    desired_kl: 0.01

    # Action bound loss
    action_bound_loss_weight: 1.0

    num_steps_per_env: 32
    save_interval: 100

    load_optimizer: True

    init_noise_std: 0.8

    num_learning_iterations: 100000
    init_at_random_ep_len: True
    eval_callbacks: null

    # actor config
    tanh_loc: False
    fixed_std: false
    up_scale: 5.0

    # Actor type selection - can be: PPOActor, PPOLogStdActor, PPOActorTanh, PPOActorFixSigma
    actor:
      _target_: humanoidverse.agents.modules.ppo_modules.PPOActor
      obs_dim_dict: ???
      module_config_dict: ${algo.config.module_dict.actor}
      num_actions: ${env.config.robot.actions_dim}
      init_noise_std: ${algo.config.init_noise_std}
      fixed_std: ${algo.config.fixed_std}
      tanh_loc: ${algo.config.tanh_loc}
      up_scale: ${algo.config.up_scale}

    module_dict:
      actor: 
        input_dim: [actor_obs]
        output_dim: [robot_action_dim]
        layer_config:
          type: MLP
          hidden_dims: [512, 256, 128]
          activation: ELU
      critic: 
        type: MLP
        input_dim: [critic_obs]
        output_dim: [1]
        layer_config:
          type: MLP
          hidden_dims: [768, 256, 128]
          activation: ELU