# @package _global_

domain_rand:
  # push robots
  push_robots : True
  push_interval_s : [10.0, 10.0]
  max_push_vel_xy : 0.5

  # base com
  randomize_base_com : False
  base_com_range:
    x : [-0.1, 0.1]
    y : [-0.1, 0.1]
    z : [-0.1, 0.1]

  # link mass
  randomize_link_mass : False
  link_mass_range : [0.8, 1.2]

  # pd gain
  randomize_pd_gain : True
  kp_range : [0.925, 1.05]
  kd_range : [0.925, 1.05]

  # friction
  randomize_friction : True
  friction_range : [0.2, 1.1]

  # base mass
  randomize_base_mass : False

  # rfi
  randomize_torque_rfi : False
  rfi_lim : 0.1
  randomize_rfi_lim : True
  rfi_lim_range : [0.5, 1.5]


  # control delay
  randomize_ctrl_delay : True
  ctrl_delay_step_range : [1, 2] # integer max real delay is 90ms